### ISSUE TITLE
Simulation  / Next chronon crashes

### ISSUE THREAD

**Issue by hroncok** [stejsle1/wator#3]
```
Traceback (most recent call last):
  File ".../stejsle1/wator/wator/gui.py", line 330, in <lambda>
    action5.triggered.connect(lambda: simulation(window, grid, app))
  File ".../stejsle1/wator/wator/gui.py", line 251, in simulation
    wator.setAge_fish(age_fish)
AttributeError: 'WaTor' object has no attribute 'setAge_fish'
```

**Comment by stejsle1** [comment]
Ahoj, 
diky za feedback. Koukala jsem na to, ale nenasla jsem problem. Stahla jsem repozitar, vytvorila cisty virtualenv, spustila - zkusila zmenit `Age of fish`, spustila `Next chronon` i `Simulation`, ale nenasla chybu. Ve `wator/wator.pyx` na konci je funkce 'setAge_fish', soubor je v `setup.py`. Muzu se zeptat, cim jsi chybu vyprovokoval? Diky

**Comment by hroncok** [comment]
Oh, this was just some old wator module being imported, false alarm, sorry. Working in a clean repo fixes the problem.
